name: bloodp
description: A Blood Pressure Management System.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.69.0
  flutter_local_notifications: ^17.2.4
  intl: ^0.19.0
  http: ^1.2.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"